//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularKanban.DBContext
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class cardlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cardlist()
        {
            this.cards = new HashSet<cards>();
            this.subcardlist = new HashSet<subcardlist>();
        }
    
        public decimal Id { get; set; }
        public string name { get; set; }
        public string color { get; set; }
        public byte orders { get; set; }
        public string created_at { get; set; }
        public decimal projectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<cards> cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<subcardlist> subcardlist { get; set; }
        [JsonIgnore]
        public virtual projects projects { get; set; }
    }
}
