//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularKanban.DBContext
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cards()
        {
            this.tasks = new HashSet<tasks>();
        }
    
        public decimal Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal cardListId { get; set; }
        public bool isExpanded { get; set; }
        public int orders { get; set; }
        public string created_at { get; set; }
        public string parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tasks> tasks { get; set; }
    }
}
